# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Plugin

on: 
  push:
    tags:
    - '*'

env:
  PLUGIN_NAME: logseq-wypst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.10.x"
        
    - name: Build
      id: build
      run: |
        npm update
        npm run build
        mkdir ${{ env.PLUGIN_NAME }}
        cp README.md package.json ${{ env.PLUGIN_NAME }}
        mv dist ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        ls
        echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
        
    - name: Create Release
      uses: ncipollo/release-action@v1.20.0
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.ref }}
      with:
        allowUpdates: true
        draft: false
        prerelease: false
        
    - name: Upload zip file
      id: upload_zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ env.PLUGIN_NAME }}.zip
        asset_name: ${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip
        asset_content_type: application/zip
 
    - name: Upload package.json
      id: upload_metadata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package.json
        asset_name: package.json
        asset_content_type: application/json
